15 March 2004 Radu Ursu - introduced lock file in autotest_cgal

diff --git a/Packages/Scripts/developer_scripts/autotest_cgal b/Packages/Scripts/developer_scripts/autotest_cgal
--- a/Packages/Scripts/developer_scripts/autotest_cgal
+++ b/Packages/Scripts/developer_scripts/autotest_cgal
@@ -43,6 +43,7 @@ ACTUAL_DIR=`pwd`
 FTP="ftp"
 LOGS_DIR="${CGAL_ROOT}/AUTOTEST_LOGS"
 RSH="rsh"
+LOCK_FILE="${CGAL_ROOT}/autotest_cgal.lock"
 if [ -f $HOME/.autocgalrc ]; then
   . $HOME/.autocgalrc
 else
@@ -143,6 +144,7 @@ error()
             ${SENDMAIL} -s "completed autotest" ${i}
       done
     fi
+    rm -rf $LOCK_FILE;
     exit 1
 }
 
@@ -421,9 +423,14 @@ if [ "${MYSHELL}" = "must_be_set_in_.autocgalrc" ]; then
   CRITICAL="y"
 fi
 if [ "${CRITICAL}" = "y" ]; then
-  exit 1;
+  error "COULD NOT DETERMINE MYSHELL!"
 fi
 
+lockfile -r 5 $LOCK_FILE;
+if [ ${?} != 0 ]; then
+  echo "COULD NOT AQUIRE LOCK!";
+  exit 1;
+fi
 
 if [ -r "LATEST" ]; then
   rm -rf LATEST
@@ -534,6 +541,6 @@ run_test
 cd ${CGAL_ROOT}
 cp LATEST RELEASE_NR
 
-  fi
-
+fi
+rm -rf $LOCK_FILE;
 # EOF
