Use unique names for example, demo and test targets Renamed CGAL-Qt as CGAL-Qt3 Re-spelled cgal components as CORE, ImageIO, PDB, Qt3 and Qt4

diff --git a/Scripts/scripts/cgal_create_cmake_script b/Scripts/scripts/cgal_create_cmake_script
--- a/Scripts/scripts/cgal_create_cmake_script
+++ b/Scripts/scripts/cgal_create_cmake_script
@@ -26,14 +26,11 @@
 # This script creates a CGAL cmake script with entries for all .C and .cpp
 # files in the current directory.
 #
-# Usage: cgal_create_cmake_script [-options]
+# Usage: cgal_create_cmake_script -tTYPE
 #
-# -q   create a CGAL cmake script with Qt support
-
+#  echo "  TYPE can be any of DEMO, EXAMPLE or TEST.. any other value is ignored"
 
 #VERSION=2.0
-
-
 
 create_cmake_script()
 {
@@ -42,7 +39,7 @@ create_cmake_script()
   echo '# This is the CMake script for compiling a CGAL application.'
   echo
   
-  echo "project( ${PROJECT} ) "
+  echo "project( ${PROJECT}_${TYPE} ) "
   echo
   echo 'CMAKE_MINIMUM_REQUIRED(VERSION 2.4.5)'
   echo
@@ -50,25 +47,19 @@ create_cmake_script()
   echo
 
   
-  if [ -n "$QT" ] ; then
+  if [ "${TYPE}" = "demo" ] ; then
   
-    echo 'find_package(CGAL REQUIRED CGAL_CORE CGAL_QT )'
-    echo
     echo 'find_package(Qt3 REQUIRED)'
     echo
+    echo 'find_package(CGAL REQUIRED CORE Qt3 )'
     echo
     echo 'include( ${CGAL_USE_FILE} )'
     echo 'include( Qt3Macros )'
     echo
     
+    target_name="${PROJECT}_${TYPE}"
+    
     for file in `ls *.C *.cpp 2>/dev/null | sort` ; do
-      # Create an executable for each cpp that  contains a function "main()"
-      BASE=`basename $file .C`
-      BASE=`basename $BASE .cpp`
-      egrep '\bmain[ \t]*\(' $file >/dev/null 2>&1
-      if [ $? -eq 0 ]; then
-        exe_name=$BASE
-      fi
       all="$all $file"
     done
     
@@ -85,21 +76,21 @@ create_cmake_script()
     fi
     echo
     
-    echo "add_executable  (${exe_name} ${all})"
+    echo "add_executable  (${target_name} ${all})"
     echo
-    echo "add_to_cached_list( CGAL_EXECUTABLES ${exe_name} )"
+    echo "add_to_cached_list( CGAL_EXECUTABLE_TARGETS ${target_name} )"
     echo
       
     echo '# Link the executable to CGAL and third-party libraries'
     echo 'if ( AUTO_LINK_ENABLED )'
-    echo "   target_link_libraries(${exe_name}"' ${QT_LIBRARIES} ${CGAL_3RD_PARTY_LIBRARIES}  )'
+    echo "   target_link_libraries(${target_name}"' ${QT_LIBRARIES} ${CGAL_3RD_PARTY_LIBRARIES}  )'
     echo 'else()'
-    echo "  target_link_libraries(${exe_name}" ' ${QT_LIBRARIES} ${CGAL_3RD_PARTY_LIBRARIES} ${CGAL_LIBRARIES} )'
+    echo "  target_link_libraries(${target_name}" ' ${QT_LIBRARIES} ${CGAL_3RD_PARTY_LIBRARIES} ${CGAL_LIBRARIES} )'
     echo 'endif()'
     
   else
   
-    echo 'find_package(CGAL REQUIRED CGAL_CORE )'
+    echo 'find_package(CGAL REQUIRED CORE )'
     echo
     echo
     echo 'include( ${CGAL_USE_FILE} )'
@@ -117,7 +108,7 @@ create_cmake_script()
       BASE=`basename $BASE .cpp`
       egrep '\bmain[ \t]*\(' $file >/dev/null 2>&1
       if [ $? -eq 0 ]; then
-        echo "create_single_source_cgal_program( $file )"
+        echo "create_single_source_cgal_program( \"${PROJECT}_${TYPE}\" \"$file\" )"
       fi
     done
   fi
@@ -129,27 +120,31 @@ create_cmake_script()
 
 usage()
 {
-     echo "Usage: cgal_create_cmake_script [-options]"
-     echo
-     echo "-q   create a CGAL CMake script with Qt support"
+  echo "Usage: cgal_create_cmake_script [TYPE]"
+  echo
+  echo "  TYPE must be any of example, demo or test."
+  echo "  Defaukt is example."
+  echo 
 }
 
 
 case $# in
-  0) ;;
-  1) ;;
+  0) TYPE="example";;
+  1) TYPE=$1;;
   *) usage
      exit 1
 esac
 
 
-for i do
-  case $i in
-    -q) QT='y';;
-    *) usage
-        exit 1;;
-  esac
-done
+
+if [ "${TYPE}" = "example" -o "${TYPE}" = "demo" -o "${TYPE}" = "test" ]; then
+  ok='y'
+fi 
+
+if [ -z "$ok" ]; then
+  echo "Invalid type: ${TYPE}. Valid values are example, demo or test"
+  exit 1
+fi 
 
 OUTPUTFILE=CMakeLists.txt
 PROJECT=`basename $PWD`
