Adapt the script rename_a_test_platform to Git

diff --git a/Maintenance/infrastructure/scripts/rename_a_test_platform b/Maintenance/infrastructure/scripts/rename_a_test_platform
--- a/Maintenance/infrastructure/scripts/rename_a_test_platform
+++ b/Maintenance/infrastructure/scripts/rename_a_test_platform
@@ -2,6 +2,7 @@
 
 DEBUG=
 SVN=
+GIT=
 
 function usage() {
     echo "Usage:"
@@ -27,7 +28,7 @@ NEW=$2
 [ -d "$OLD" ] || error "\"%s\" does not seem to be a directory.\n" "$OLD"
 [ -e "$OLD/CMakeCache.txt" ] || error "\"%s\" does not seem to be a platform directory.\n" "$OLD"
 
-if grep -q CGAL_REFERENCE_CACHE_DIR "$OLD/CMakeCache.txt"; then 
+if grep -q CGAL_REFERENCE_CACHE_DIR "$OLD/CMakeCache.txt"; then
     error "\"%s\" seems to be\n       the cache of a test platform directory in use in the testsuite, and\n       not the cache of a *reference* test platform.\n       Reason: the cache contains a variable CGAL_REFERENCE_CACHE_DIR.\n" "$OLD/CMakeCache.txt"
 fi
 
@@ -35,7 +36,10 @@ fi
 
 if [ -e "$OLD/.svn" ]; then
   SVN=y
-  $DEBUG svn cp "$OLD/" "$NEW" || error "Cannot \"svn cp\" from \"%s\" to \"%s\"\n" "$OLD" "$NEW"
+  $DEBUG svn cp "$OLD/" "$NEW" ||  error "Cannot \"svn cp\" from \"%s\" to \"%s\"\n" "$OLD" "$NEW"
+elif git rev-parse; then
+  GIT=y
+  $DEBUG git mv "$OLD/" "$NEW" ||  error "Cannot \"git mv\" from \"%s\" to \"%s\"\n" "$OLD" "$NEW"
 else
   $DEBUG rsync -aC "$OLD/" "$NEW" || error "Cannot copy from \"%s\" to \"%s\"\n" "$OLD" "$NEW"
 fi
@@ -43,6 +47,6 @@ $DEBUG sed -i.bak -e "s,$OLD,$NEW,g" "$NEW"/CMakeCache.txt
 [ -e "$NEW/setup" ] && sed -i.bak -e 's|$OLD|$NEW|g' "$NEW"/setup
 if [ -n "$SVN" ]; then
   $DEBUG svn rm "$OLD"
-else 
+else
   $DEBUG rm -rf "$OLD" || error "Cannot erase the original directory \"%s\"\n" "$OLD"
 fi
