Workaround a problem with a clean target under cygwin+nmake

diff --git a/Scripts/developer_scripts/create_cgal_test_with_cmake b/Scripts/developer_scripts/create_cgal_test_with_cmake
--- a/Scripts/developer_scripts/create_cgal_test_with_cmake
+++ b/Scripts/developer_scripts/create_cgal_test_with_cmake
@@ -113,8 +113,6 @@ compile_and_run()
       echo   "   ERROR:    not executed   \$1" >> \$ERRORFILE
     fi
   fi
-
-  make -fMakefile clean
 }
 
 EOF
@@ -141,7 +139,18 @@ EOF
       echo "  compile_and_run $tmp"
     fi
   done
-  echo "fi"
+cat << EOF
+fi
+
+#
+# The clean target generated by CMake under cygwin 
+# always fails for some reason
+#
+if ! ( uname | grep -q "CYGWIN" ) ; then
+  make -fMakefile clean
+fi
+EOF
+  
 }
 
 echo "create_cgal_test_with_cmake version $VERSION"
