check cmake scripts of tests, examples and demos exist

diff --git a/Scripts/developer_scripts/test_merge_of_branch b/Scripts/developer_scripts/test_merge_of_branch
--- a/Scripts/developer_scripts/test_merge_of_branch
+++ b/Scripts/developer_scripts/test_merge_of_branch
@@ -82,23 +82,33 @@ else
     echo 'No new files.'
 fi
 
-project_name_tests=$(for i in */test/*/CMakeLists.txt; do pkg=$(echo $i | awk -F "/" '{print $3}'); grep ${pkg}_Tests -L $i;  done)
-project_name_examples=$(for i in */examples/*/CMakeLists.txt; do pkg=$(echo $i | awk -F "/" '{print $3}'); grep ${pkg}_Examples -L $i;  done)
-project_name_demo=$(for i in */demo/*/CMakeLists.txt; do pkg=$(echo $i | awk -F "/" '{print $3}'); grep ${pkg}_Demo -L $i;  done)
+#check cmake scripts of tests, examples are present
+for i in `ls -d */examples/*/ */test/*/`; do
+  if ! [ -f $i/CMakeLists.txt ]; then
+    echo "Error: $i/CMakeLists.txt does not exist!"
+    exit 1
+  fi
+done
 
-if [ -n "${project_name_tests}" ]; do
+
+# check project in cmake scripts is correct
+project_name_tests=$(for i in */test/*/CMakeLists.txt; do pkg=$(echo $i | awk -F "/" '{print $3}'); egrep "${pkg}_Tests\s*\)" -L $i;  done)
+project_name_examples=$(for i in */examples/*/CMakeLists.txt; do pkg=$(echo $i | awk -F "/" '{print $3}'); egrep "${pkg}_Examples\s*\)" -L $i;  done)
+project_name_demo=$(for i in */demo/*/CMakeLists.txt; do pkg=$(echo $i | awk -F "/" '{print $3}'); egrep "${pkg}_Demo\s*\)" -L $i;  done)
+
+if [ -n "${project_name_tests}" ]; then
   echo "CMakeLists with incorrect project name"
   echo ${project_name_tests}
   exit 1
 fi
 
-if [ -n "${project_name_examples}" ]; do
+if [ -n "${project_name_examples}" ]; then
   echo "CMakeLists with incorrect project name"
   echo ${project_name_examples}
   exit 1
 fi
 
-if [ -n "${project_name_demo}" ]; do
+if [ -n "${project_name_demo}" ]; then
   echo "CMakeLists with incorrect project name"
   echo ${project_name_demo}
   exit 1
