Fix indentation

diff --git a/Surface_sweep_2/test/Surface_sweep_2/cgal_test_base b/Surface_sweep_2/test/Surface_sweep_2/cgal_test_base
--- a/Surface_sweep_2/test/Surface_sweep_2/cgal_test_base
+++ b/Surface_sweep_2/test/Surface_sweep_2/cgal_test_base
@@ -78,12 +78,12 @@ compile()
 
 compile_and_run()
 {
-
+    
   echo "---$1---"
 
   # running general test
   if compile $1 $2 $3 ; then
-    echo "   compilation of $1 succeeded" >> $ERRORFILE
+    echo "   compilation of $1 succeeded" >> $ERRORFILE  
     SUBCURVES=""
     run $1 $2 $3 $4
     SUBCURVES="subcurves"
@@ -100,14 +100,14 @@ clean_tests()
 {
     if [ "${TEST_WITH_CMAKE}" != "FALSE" ]; then
     #
-    # The clean target generated by CMake under cygwin
+    # The clean target generated by CMake under cygwin 
     # always fails for some reason
     #
-  if ! ( uname | grep -q "CYGWIN" ) ; then
-      "${MAKE_CMD}" -f Makefile clean
-  fi
+	if ! ( uname | grep -q "CYGWIN" ) ; then
+	    "${MAKE_CMD}" -f Makefile clean
+	fi
     else
-  eval "${MAKE_CMD} clean > /dev/null 2>&1"
+	eval "${MAKE_CMD} clean > /dev/null 2>&1"
     fi
 }
 
@@ -117,7 +117,7 @@ compile_and_run_sweep()
 
   # running general test
   if compile $1 $2 $3 ; then
-    echo "   compilation of $1 succeeded" >> $ERRORFILE
+    echo "   compilation of $1 succeeded" >> $ERRORFILE  
     run $1 $2 $3 $4
   else
     echo "   ERROR: compilation of $1 failed" >> $ERRORFILE
@@ -134,28 +134,28 @@ run()
   for DATAFILE in ${datafiles}
   do
     if [ -d $DATAFILE ]; then
-        echo  "$DATEFILE is a directory"
+        echo  "$DATEFILE is a directory" 
         continue
     fi
 
     if [ -f $1 ] ; then
         DATANAME=`basename $DATAFILE`
-  if [ $SUBCURVES="subcurves" ] ; then
-      OUTPUTFILE=ProgramOutput.$3.$1.$DATANAME.$SUBCURVES.$PLATFORM.$2
+	if [ $SUBCURVES="subcurves" ] ; then
+	    OUTPUTFILE=ProgramOutput.$3.$1.$DATANAME.$SUBCURVES.$PLATFORM.$2
         else
-      OUTPUTFILE=ProgramOutput.$3.$1.$DATANAME.$PLATFORM.$2
-  fi
-  rm -f $OUTPUTFILE
-  COMMAND="./$1 $DATAFILE $SUBCURVES"
-  echo "Executing $1 $DATANAME $SUBCURVES ... "
-  echo
-  if eval $COMMAND > $OUTPUTFILE 2>&1 ; then
-  echo "   execution of $1 $DATAFILE $SUBCURVES succeeded" >> $ERRORFILE
-  else
-  echo "   ERROR: execution of $1 $DATAFILE $SUBCURVES failed" >> $ERRORFILE
-  fi
+	    OUTPUTFILE=ProgramOutput.$3.$1.$DATANAME.$PLATFORM.$2
+	fi
+	rm -f $OUTPUTFILE
+	COMMAND="./$1 $DATAFILE $SUBCURVES"
+	echo "Executing $1 $DATANAME $SUBCURVES ... "
+	echo
+	if eval $COMMAND > $OUTPUTFILE 2>&1 ; then
+	echo "   execution of $1 $DATAFILE $SUBCURVES succeeded" >> $ERRORFILE
+	else
+	echo "   ERROR: execution of $1 $DATAFILE $SUBCURVES failed" >> $ERRORFILE
+	fi
     else
-  echo "   ERROR: could not execute $1 $DATAFILE $SUBCURVES" >> $ERRORFILE
+	echo "   ERROR: could not execute $1 $DATAFILE $SUBCURVES" >> $ERRORFILE
     fi
   done
 
@@ -178,33 +178,33 @@ run_io()
 
   for DATAFILE in ${datafiles}
   do
-
+    
     if [ -d $DATAFILE ]; then
-        echo  "$DATEFILE is a directory"
+        echo  "$DATEFILE is a directory" 
         continue
     fi
-
+    
     IOFILE="${iofiles}`basename ${DATAFILE}`_${SUFFIO}"
     echo $IOFILE
-
+    
     if [ -f $1 ] ; then
         rm -f arr.txt
-
+        
         DATANAME=`basename $DATAFILE`
-        IONAME=`basename $IOFILE`
+        IONAME=`basename $IOFILE`	
         OUTPUTFILE=ProgramOutput.$3.$1.$DATANAME.$PLATFORM.$2
 
-  rm -f $OUTPUTFILE
-  COMMAND="./$1 $IOFILE $DATAFILE"
-  echo "Executing $1 $IONAME $DATANAME  ... "
-  echo
-  if eval $COMMAND > $OUTPUTFILE 2>&1 ; then
-  echo "   execution of $1 $DATAFILE succeeded" >> $ERRORFILE
-  else
-  echo "   ERROR: execution of $1 $DATAFILE  failed" >> $ERRORFILE
-  fi
+	rm -f $OUTPUTFILE
+	COMMAND="./$1 $IOFILE $DATAFILE"
+	echo "Executing $1 $IONAME $DATANAME  ... "
+	echo
+	if eval $COMMAND > $OUTPUTFILE 2>&1 ; then
+	echo "   execution of $1 $DATAFILE succeeded" >> $ERRORFILE
+	else
+	echo "   ERROR: execution of $1 $DATAFILE  failed" >> $ERRORFILE
+	fi
     else
-  echo "   ERROR: could not execute $1 $DATAFILE " >> $ERRORFILE
+	echo "   ERROR: could not execute $1 $DATAFILE " >> $ERRORFILE
     fi
   done
 
@@ -224,8 +224,8 @@ touch $ERRORFILE
 
 if [ $# -ne 0 ] ; then
     case $1 in
-  -cmake) TEST_WITH_CMAKE="TRUE" ;;
-  *)TEST_WITH_CMAKE="FALSE" ;;
+	-cmake) TEST_WITH_CMAKE="TRUE" ;;
+	*)TEST_WITH_CMAKE="FALSE" ;;
     esac
 else
     TEST_WITH_CMAKE="FALSE"
