Changed the implementation of wait_for_process. It now uses kill -CONT to check if a process (still) exists. It send a kill -TERM signal to the process only, not to the process group.

diff --git a/Packages/Scripts/test/run_testsuite b/Packages/Scripts/test/run_testsuite
--- a/Packages/Scripts/test/run_testsuite
+++ b/Packages/Scripts/test/run_testsuite
@@ -22,28 +22,50 @@ ERRORFILE=${CURRENTDIR}/error.txt
 rm -f $ERRORFILE
 touch $ERRORFILE
 
+# Wait for process with pid $1.
+# Wait for $2 periods of $3 seconds, checking after every period
+# if the watched process has finished.
 wait_for_process()
 {
-    count=$2
-    while [ $count -ne 0 ]
+    pid=$1;
+    cycles=$2
+    period=$3
+    while [ $cycles -ne 0 ]
     do
-	count=`expr $count - 1`
-	if ps |grep $1 >/dev/null
-	then
-	    sleep $3
-	else
-	    count=0
+        cycles=`expr $cycles - 1`  
+# send SIGCONT to the process and check the exit value of kill.
+# If the process still exists, the call to kill succeeds (and the signal is
+# ignored).
+        
+        kill -CONT $pid 2>kill_output 1>/dev/null;   terminated=$?
+# But under CYGWIN the exit status is not to be trusted.
+	if [ $terminated -eq 0 ]; then
+	    if grep -i 'no such process' kill_output; then
+		terminated=1;
+	    fi
 	fi
+	rm -f kill_output
+	if [ $terminated -eq 0 ]
+        then
+            sleep $period
+        else
+            cycles=0
+            running=0
+        fi
     done
-
-    if ps |grep $1 >/dev/null
+    if [ $terminated -eq 0 ]
     then
+    	if false; then
 # Send signal Terminate (SIGTERM) to the whole process group.
 # First disable the default action (quit) for the current process.
-        trap true 15
-        kill -15 0
-        trap 15
-        return 1
+	    trap true TERM
+	    kill -TERM 0
+	    trap TERM
+	else
+# But for the moment only send SIGTERM to the process itself.
+	    kill -TERM $pid
+	fi
+        return 1  
     fi
     return 0
 }
