removed redundant arguments to cmake

diff --git a/Snap_rounding_2/test/Snap_rounding_2/cgal_test_base b/Snap_rounding_2/test/Snap_rounding_2/cgal_test_base
--- a/Snap_rounding_2/test/Snap_rounding_2/cgal_test_base
+++ b/Snap_rounding_2/test/Snap_rounding_2/cgal_test_base
@@ -23,19 +23,16 @@ fi
 
 configure()
 {
-    echo "Configuring... "
+  echo "Configuring... "
     
-    if eval 'cmake "$CMAKE_GENERATOR" -DRUNNING_CGAL_AUTO_TEST=TRUE  \
+  if eval 'cmake "$CMAKE_GENERATOR" -DRUNNING_CGAL_AUTO_TEST=TRUE  \
                                      -DCGAL_DIR="$CGAL_DIR" \
-                                     -DCGAL_CXX_FLAGS:STRING="$TESTSUITE_CXXFLAGS" \
-                                     -DCGAL_EXE_LINKER_FLAGS="$TESTSUITE_LDFLAGS" \
-                                     -DCMAKE_BUILD_TYPE=NOTFOUND \
                                      .' ; then
         
-	echo "   succesful configuration" >> $ERRORFILE
-    else
-	echo "   ERROR:    configuration" >> $ERRORFILE
-    fi
+    echo "   succesful configuration" >> $ERRORFILE
+  else
+    echo "   ERROR:    configuration" >> $ERRORFILE
+  fi
 }
 
 
@@ -51,22 +48,21 @@ compile()
 
   if [ "${TEST_WITH_CMAKE}" != "FALSE" ]; then
       
-      export TESTSUITE_CXXFLAGS="-DCGAL_SNAP_ROUNDING_TEST=$2"
-      configure
-      if eval '${MAKE_CMD} VERBOSE=1 -fMakefile  \
-            $1' ; then
-	  echo "   compilation of $1 succeeded" >> $ERRORFILE
-      else
-	  echo "   ERROR: compilation of $1 failed" >> $ERRORFILE
-      fi
-      else
-      if eval 'make CGAL_MAKEFILE=$CGAL_MAKEFILE \
-           TESTSUITE_CXXFLAGS="$TESTSUITE_CXXFLAGS" \
-           TESTSUITE_LDFLAGS="$TESTSUITE_LDFLAGS" $1' ; then
-	  echo "   compilation of $1 succeeded" >> $ERRORFILE
-      else
-	  echo "   ERROR: compilation of $1 failed" >> $ERRORFILE
-      fi
+    export TESTSUITE_CXXFLAGS="-DCGAL_SNAP_ROUNDING_TEST=$2"
+    configure
+    if eval '${MAKE_CMD} VERBOSE=1 -fMakefile $1' ; then
+      echo "   compilation of $1 succeeded" >> $ERRORFILE
+    else
+      echo "   ERROR: compilation of $1 failed" >> $ERRORFILE
+    fi
+    else
+    if eval 'make CGAL_MAKEFILE=$CGAL_MAKEFILE \
+       TESTSUITE_CXXFLAGS="$TESTSUITE_CXXFLAGS" \
+       TESTSUITE_LDFLAGS="$TESTSUITE_LDFLAGS" $1' ; then
+      echo "   compilation of $1 succeeded" >> $ERRORFILE
+    else
+      echo "   ERROR: compilation of $1 failed" >> $ERRORFILE
+    fi
   fi
 }
 
@@ -88,16 +84,16 @@ run()
       echo "Executing ./$1 $DATAFILE > ${data_dir}/out"
       echo
       if eval 2>&1 $COMMAND > $OUTPUTFILE ; then
-	  echo "   execution of $1 ${data_dir}/$DATATFILE > ${data_dir}/out succeeded" >> $ERRORFILE
-	  if ${CMP}  ${data_dir}/out "${data_dir}/gold_$DATANAME" ; then
-	      echo "   no differences between output and gold were found" >> $ERRORFILE
-	  else
-	      echo "   ERROR:  differences between output and gold were found" >> $ERRORFILE
-	      echo "   ERROR:  differences between output and gold were found :" >> $OUTPUTFILE
-              diff ${data_dir}/out "${data_dir}/gold_$DATANAME" >> $OUTPUTFILE
-	  fi
+	echo "   execution of $1 ${data_dir}/$DATATFILE > ${data_dir}/out succeeded" >> $ERRORFILE
+	if ${CMP}  ${data_dir}/out "${data_dir}/gold_$DATANAME" ; then
+	  echo "   no differences between output and gold were found" >> $ERRORFILE
+	else
+	  echo "   ERROR:  differences between output and gold were found" >> $ERRORFILE
+	  echo "   ERROR:  differences between output and gold were found :" >> $OUTPUTFILE
+          diff ${data_dir}/out "${data_dir}/gold_$DATANAME" >> $OUTPUTFILE
+	fi
       else
-	  echo "   ERROR: execution of $1 $DATAFILE $2 ${data_dir}/out failed" >> $ERRORFILE
+	echo "   ERROR: execution of $1 $DATAFILE $2 ${data_dir}/out failed" >> $ERRORFILE
       fi
     else
       echo "   ERROR: could not execute $1" >> $ERRORFILE
@@ -117,18 +113,18 @@ run()
 #---------------------------------------------------------------------#
 
   if [ $# -ne 0 ] ; then
-      case $1 in
-	  -cmake) TEST_WITH_CMAKE="TRUE" ;;
-	  *)TEST_WITH_CMAKE="FALSE" ;;
-      esac
+    case $1 in
+      -cmake) TEST_WITH_CMAKE="TRUE" ;;
+      *)TEST_WITH_CMAKE="FALSE" ;;
+    esac
   else
-      TEST_WITH_CMAKE="FALSE"
+    TEST_WITH_CMAKE="FALSE"
   fi
   
   echo "Run all tests."
   
   if [ "${TEST_WITH_CMAKE}" != "FALSE" ]; then
-      configure
+    configure
   fi
   
 
@@ -140,11 +136,11 @@ run()
     # The clean target generated by CMake under cygwin 
     # always fails for some reason
     #
-      if ! ( uname | grep -q "CYGWIN" ) ; then
-	  make -fMakefile clean
-      fi
+    if ! ( uname | grep -q "CYGWIN" ) ; then
+      make -fMakefile clean
+    fi
   else
-      eval "2>&1 make CGAL_MAKEFILE=$CGAL_MAKEFILE clean > /dev/null " 
+    eval "2>&1 make CGAL_MAKEFILE=$CGAL_MAKEFILE clean > /dev/null " 
   fi
 
 #EOF
